# templates/configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmaptenjin
data:
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-postgres:5432/{{ .Values.environment.POSTGRES_DB }}"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.environment.POSTGRES_USER }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.environment.POSTGRES_PASSWORD }}"
  TENJIN_DEFAULT_USER_PASSWORD: "{{ .Values.environment.DEFAULT_USER_PASSWORD }}"
  TENJIN_ELASTIC_HOST: "{{ .Release.Name }}-elasticsearch"
  TENJIN_ELASTIC_PORT: "9200"
  TENJIN_ELASTIC_USERNAME: "elastic"
  TENJIN_ELASTIC_SECURETYPE: "http"
  TENJIN_BASE_URL: "{{ .Values.environment.TENJIN_HOST_NAME }}"
  TENJIN_ALLOWED_URL: "{{ .Values.environment.TENJIN_ALLOWED_URL }}"
  TENJIN.AI-HOST: http://{{ .Release.Name }}-tenjin-ai:8022